Refactor/blog/post
GDSC-Daejin/gdsc-dju-websites pull request #101
Opened 2022-08-28 10:55 UTC by HyeokE

## 작업 내용 (Content)

## 기타 사항 (Etc)

## Merge 전 필요 작업 (Checklist before merge)
- [ ] component 대소문자 확인
- [ ] conflict 해결
- [ ] tsc 오류 확인

## Merge 후 필요 작업 (Checklist after merge)
- PR이 생성되면 코드 리뷰 요청한 개발자에게 슬랙으로 알려주세요.

2022-09-05 07:06 UTC, bjc1102 requested changes

2022-09-05 07:25 UTC, HyeokE commented on packages/gdsc-dju-blog/src/api/hooks/useGetNewToken.ts
> +  if (response.data.header.code == 401) return;
저희 쪽 문제가 토큰이 만료된 상태에서 블로그에 접속시 token을 재발급 받아야하는데요.
토큰이 재발급된 후 유저 데이터를 가져와야해서 저런 로직을 넣었어요.
콜리가 언급해주신 것보면 요청이 성공한 후에 아래 같은 코드가 나오는데요
- 401 만료되지 않음 
- 403 리프레시 토큰이 만료됨
- 200 재발급 성공
만료되지 않았을 때(401)는 기존토큰으로 데이터 요청
만료시 재발급 후 새로운 토큰으로 데이터 요청

2022-09-05 07:28 UTC, HyeokE commented on packages/gdsc-dju-blog/src/Layout/index.tsx
>  const Layout = () => {
으음 Route로 치기에는 내부에 ComponentLayout이 들어가서 좀 애매한 것 같아요.
중심이 되는 코드니까 Core는 어떠신가요

2022-09-05 08:34 UTC, bjc1102 commented on packages/gdsc-dju-blog/src/Layout/index.tsx
>  const Layout = () => {
Core도 좋은거같아요 아니면 파일을 더 분리할까요?

2022-09-05 08:35 UTC, bjc1102 commented on packages/gdsc-dju-blog/src/api/hooks/useGetNewToken.ts
> +  if (response.data.header.code == 401) return;
이해했습니다 ㅎㅎ

2022-09-05 09:13 UTC, gudcks0305 commented on packages/gdsc-dju-blog/src/api/hooks/useGetNewToken.ts
> +  if (response.data.header.code == 401) return;
음... 개인적으로 인터셉터를 전역 등록해서 사용하셨으면 좋겠네요. auth가 필요한 api 가 많은데 
- token refresh는 mydata 밖에 없는 문제가 있어요
  - 이 문제가 어떤 문제냐면 글 작성 하다가 자료 찾다가 시간 지나면 임시 저장도 안되고 401 에러 떠서 있는 내용 다 날려야 되는 문제가 있어요 
- 지속적으로 main Page에서 myinfo request 를 하는  문제가 있어요 
- token refresh 이후에 사실 MyInfo 를 다시 불러올 필요는 없다고 생각되고 update , Login , MyBlog 입장 시 에만 MyInfo 불러오면 된다고 생각 돼요 velog 가 그러함 
- 참고자료 : https://slog.website/post/10

2022-09-05 10:25 UTC, bjc1102 commented on packages/gdsc-dju-blog/src/api/hooks/useGetNewToken.ts
> +  if (response.data.header.code == 401) return;
axios instance만 파서 붙이면 될거같긴해요

2022-09-07 08:21 UTC, HyeokE commented on packages/gdsc-dju-blog/src/api/hooks/useGetNewToken.ts
> +  if (response.data.header.code == 401) return;
instance 추가했습니다.
cookie expire date 로직만 추가하면 될 것 같아요.

2022-09-07 08:28 UTC, HyeokE commented on packages/gdsc-dju-blog/src/api/hooks/useGetNewToken.ts
> +  if (response.data.header.code == 401) return;
> 음... 개인적으로 refresh 로직은 axios 인터셉터로 전역 등록해서 사용하셨으면 좋겠네요. auth가 필요한 api 가 많은데
> 
> * token refresh 로직이 mydata 밖에 없는 문제가 있어요
>   
>   * 이 문제가 어떤 문제냐면 글 작성 하다가 자료 찾다가 시간 지나면 임시 저장도 안되고 401 에러 떠서 있는 내용 다 날려야 되는 문제가 있어요
> * 지속적으로 main Page에서 myinfo request 를 하는  문제가 있어요
> * token refresh 이후에 사실 MyInfo 를 다시 불러올 필요는 없다고 생각되고 update , Login , MyBlog 입장 시 에만 MyInfo 불러오면 된다고 생각 돼요 velog 가 그러함
> * Localstorage Info remain 유무로 request 유무를 결정해요 아마 인터셉터 사용 하시면 Myinfo request 트래픽을 줄일 수 있을 것 같고 상기 문제들 해결 가능 할 것 같아요
> * 참고자료 : https://slog.website/post/10

감사합니다.
주신 자료로 instance 추가했어요. token expire 로직만 추가하면 될 것 같아요.

2022-09-07 10:47 UTC, bjc1102 commented on packages/gdsc-dju-blog/src/api/AuthService.ts
> +const Auth = axios.create({
axios로 인스턴스를 하나 만들었으니 baseURL로 api주소를 뺴고 this.api같이 중복되는 부분을 없애도 괜찮을거같아요.

그래서 아예 create한 부분을 변수명 변경하고 class api 쪽으로 빼거나 따로 파일을 만드시는 건 어떻게 생각하시나요?

2022-09-07 15:51 UTC, HyeokE commented on packages/gdsc-dju-blog/src/api/AuthService.ts
> +const Auth = axios.create({
> axios로 인스턴스를 하나 만들었으니 baseURL로 api주소를 뺴고 this.api같이 중복되는 부분을 없애도 괜찮을거같아요.
> 
> 그래서 아예 create한 부분을 변수명 변경하고 class api 쪽으로 빼거나 따로 파일을 만드시는 건 어떻게 생각하시나요?

`그래서 아예 create한 부분을 변수명 변경하고 class api 쪽으로 빼거나 따로 파일을 만드시는 건 어떻게 생각하시나요?`
요 부분을 이해못했는데 자세히 설명해주실 수 있을까용

2022-09-08 10:40 UTC, bjc1102 commented on packages/gdsc-dju-blog/src/api/AuthService.ts
> +const Auth = axios.create({
> > axios로 인스턴스를 하나 만들었으니 baseURL로 api주소를 뺴고 this.api같이 중복되는 부분을 없애도 괜찮을거같아요.
> > 그래서 아예 create한 부분을 변수명 변경하고 class api 쪽으로 빼거나 따로 파일을 만드시는 건 어떻게 생각하시나요?
> 
> `그래서 아예 create한 부분을 변수명 변경하고 class api 쪽으로 빼거나 따로 파일을 만드시는 건 어떻게 생각하시나요?` 요 부분을 이해못했는데 자세히 설명해주실 수 있을까용

```
const instance = axios.create({
  baseURL: this.api,
  timeout: 10000,
  params: {},
});
```
이렇게 만들게 되면 조금 더 단순하게 할 수 있을거같아서요 이렇게 되면 전역 설정을 추가하기 쉬울거같아서 말씀드렸습니다
```
instance .get(`/api/guest/v1/myPost/${postId}`,
      this.Header,
    );
```

2022-09-08 15:08 UTC, HyeokE commented on packages/gdsc-dju-blog/src/api/AuthService.ts
> +const Auth = axios.create({
아 네네 이해했습니다.
```
import { refresh, refreshErrorHandler } from '@src/api/hooks/getNewToken';
import axios from 'axios';

const isProduction = process.env.NODE_ENV === 'production';

const AuthInstance = axios.create({
  timeout: 10000,
  params: {},
  baseURL: `https://api.gdsc-dju.com/${
    isProduction ? '/blog-route' : '/blog-route-dev'
  }`,
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,OPTIONS',
    'Access-Control-Allow-Headers':
      'Content-Type, Authorization, Content-Length, X-Requested-With',
  },
});
AuthInstance.interceptors.request.use(refresh, refreshErrorHandler);
AuthInstance.defaults.withCredentials = true;

const Instance = axios.create({
  timeout: 10000,
  params: {},
  baseURL: `https://api.gdsc-dju.com/`,
  headers: {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,OPTIONS',
    'Access-Control-Allow-Headers':
      'Content-Type, Authorization, Content-Length, X-Requested-With',
  },
});
Instance.interceptors.request.use();
Instance.defaults.withCredentials = true;

export { AuthInstance, Instance };

```
이런식으로 코드 짰는데 CORS가 나오네요. ㅜㅜ

2022-09-09 07:28 UTC, HyeokE commented on packages/gdsc-dju-blog/src/api/AuthService.ts
> +const Auth = axios.create({
완료! 했습니다.

```
import { refresh, refreshErrorHandler } from '@src/api/hooks/getNewToken';
import axios from 'axios';

const isProduction = process.env.NODE_ENV === 'production';

const AuthInstance = axios.create({
  timeout: 10000,
  params: {},
  baseURL: `https://api.gdsc-dju.com/`,
});
AuthInstance.interceptors.request.use(refresh, refreshErrorHandler);
AuthInstance.defaults.withCredentials = true;

const AuthBlogInstance = axios.create({
  timeout: 10000,
  params: {},
  baseURL: `https://api.gdsc-dju.com/${
    isProduction ? 'blog-route' : 'blog-route-dev'
  }`,
});
AuthBlogInstance.interceptors.request.use(refresh, refreshErrorHandler);
AuthInstance.defaults.withCredentials = true;

const Instance = axios.create({
  timeout: 10000,
  params: {},
  baseURL: `https://api.gdsc-dju.com`,
});
const BlogInstance = axios.create({
  timeout: 10000,
  params: {},
  baseURL: `https://api.gdsc-dju.com/${
    isProduction ? 'blog-route' : 'blog-route-dev'
  }`,
});
Instance.interceptors.request.use();
Instance.defaults.withCredentials = true;

export { Instance, AuthInstance, BlogInstance, AuthBlogInstance };
```

2022-09-09 07:29 UTC, HyeokE commented on packages/gdsc-dju-blog/src/Layout/index.tsx
>  const Layout = () => {
음... 더 어떻게 분리할까요 더 분리하면 정신없지 않을까요?

2022-09-10 11:33 UTC, merged