Refactor/gdsc dju blog/91 검색 css 수정
GDSC-Daejin/gdsc-dju-websites pull request #98
Opened 2022-08-25 12:02 UTC by bjc1102

## 작업 내용 (Content)
 - 검색 페이지 css 수정, 카테고리 추가, 페이지네이션
 - useScroll 커스텀훅으로 분리
 - pages/home 코드 리팩토링
 - 중복검사 기능 추가
 - 검색버튼 수정

## 기타 사항 (Etc)

## Merge 전 필요 작업 (Checklist before merge)
- [ ] component 대소문자 확인
- [ ] conflict 해결
- [ ] tsc 오류 확인

## Merge 후 필요 작업 (Checklist after merge)
- PR이 생성되면 코드 리뷰 요청한 개발자에게 슬랙으로 알려주세요.

2022-08-26 06:06 UTC, HyeokE requested changes

2022-08-26 06:06 UTC, HyeokE commented on packages/gdsc-dju-blog/src/assets/icons/CheckIcon.tsx
> +  };
const theme = useTheme();

type === 'success' ? theme.colors.green600 ? type === 'error' ? theme.colors.red600 : theme.colors.grey400

2022-08-26 06:06 UTC, HyeokE commented on packages/gdsc-dju-blog/src/assets/icons/CheckIcon.tsx
> +  };
const theme = useTheme();

if(type === 'success') theme.colors.green600
if(type === 'error') theme.colors.red600
else theme.colors.grey400

요게 더 직관적일 수도 있겠네영

2022-08-26 06:06 UTC, HyeokE commented on packages/gdsc-dju-blog/src/assets/icons/CheckIcon.tsx
> +  };
그리고 에셋을 직접 가져오는 것 말고 const theme = useTheme() 훅을 사용하시는게 더 좋은 방향 같아요.

2022-08-26 06:50 UTC, bjc1102 commented on packages/gdsc-dju-blog/src/assets/icons/CheckIcon.tsx
> +const CheckIcon = ({ isSuccess, isError }: CheckIconProps) => {
isSuccess랑 isError는 서로 다른 상태변수인데 한가지 변수로 만들 수 있나요

2022-08-27 17:23 UTC, HyeokE approved these changes

2022-08-27 17:47 UTC, HyeokE commented
develop/blog pull 해보시고 오류 없으면 머지하셔도 될 것 같습니다.

2022-08-29 06:30 UTC, merged